version: '3.5'

networks:
  solace_msg_net:
    name: solace_msg_net
    external: false
    driver: bridge

services:
  solbroker:
    image: $PUBSUB_IMAGE
    hostname: $PUBSUB_HOSTNAME
    networks:
      - solace_msg_net
    env_file:
      - ./solace_config_keys.env

    ports:
      - "2222:2222"
      - "8080:8080"
      - "55443:55443"
      - "55445:55445"
      - "${PUBSUB_PORT_NUMBER}:55555"
      - "55556:55556"
      - "5671:5671"
      - "5672:5672"
      - "5550:5550"
      - "1943:1943"
      - "8008:8008"
    shm_size: 2g
    ulimits:
      memlock: -1
      nofile:
        soft: 2448
        hard: 42192
